### ISSUE TITLE
training error.

### ISSUE THREAD

**Issue by yangxiufengsia** [mattragoza/liGAN#11]
Hi, 

when I run your train.py file. I got this error: [libprotobuf ERROR google/protobuf/message_lite.cc:244] Error computing ByteSize (possible overflow?).
F1210 06:03:40.463183  1051 io.cpp:69] Check failed: proto.SerializeToOstream(&output) 
*** Check failure stack trace: ***
Aborted (core dumped)

Do you know how to solve it? Thank you.

**Comment by mattragoza** [comment]
Can you share the model prototxt that you are using?

**Comment by yangxiufengsia** [comment]
thanks for your reply. The model prototex I used are listed as follows:
data_param.model:
# encode_type = 'data'
# data_dim = 48
# resolution = 0.5
# data_options = ''
# rec_map = 'my_rec_map'
# lig_map = 'my_lig_map'
layer {
  name: "data"
  type: "MolGridData"
  top: "data"
  top: "label"
  top: "aff"
  include {
    phase: TRAIN
  }
  molgrid_data_param {
    source: "TRAINFILE"
    batch_size: 16
    dimension: 23.5
    resolution: 0.5
    shuffle: true
    balanced: false
    root_folder: "DATA_ROOT"
    random_rotation: true
    random_translate: 2.0
    binary_occupancy: false
    recmap: "my_rec_map"
    ligmap: "my_lig_map"
    radius_multiple: 1.5
    fixed_radius: 0.0
    has_affinity: true
    use_covalent_radius: false
    recmolcache: ""
    ligmolcache: ""
  }
}
layer {
  name: "data"
  type: "MolGridData"
  top: "data"
  top: "label"
  top: "aff"
  include {
    phase: TEST
  }
  molgrid_data_param {
    source: "TESTFILE"
    batch_size: 16
    dimension: 23.5
    resolution: 0.5
    shuffle: false
    balanced: false
    root_folder: "DATA_ROOT"
    random_rotation: false
    random_translate: 0.0
    binary_occupancy: false
    recmap: "my_rec_map"
    ligmap: "my_lig_map"
    radius_multiple: 1.5
    fixed_radius: 0.0
    has_affinity: true
    use_covalent_radius: false
    recmolcache: ""
    ligmolcache: ""
  }
}
layer {
  name: "slice_rec_lig"
  type: "Slice"
  bottom: "data"
  top: "rec"
  top: "lig"
  slice_param {
    slice_point: 16
    axis: 1
  }
}


the gen_param.model:
# encode_type = '_rvl-l'
# rec_map = 'my_rec_map'
# lig_map = 'my_lig_map'
# data_dim = 48
# resolution = 0.5
# data_options = ''
# n_levels = 4
# conv_per_level = 3
# arch_options = 'l'
# n_filters = 32
# width_factor = 2
# n_latent = 1024
# loss_types = 'a'
layer {
  name: "rec"
  type: "Input"
  top: "rec"
  input_param {
    shape {
      dim: 16
      dim: 16
      dim: 48
      dim: 48
      dim: 48
    }
  }
}
layer {
  name: "lig"
  type: "Input"
  top: "lig"
  input_param {
    shape {
      dim: 16
      dim: 19
      dim: 48
      dim: 48
      dim: 48
    }
  }
}
layer {
  name: "data"
  type: "Concat"
  bottom: "rec"
  bottom: "lig"
  top: "data"
  concat_param {
    axis: 1
  }
}
layer {
  name: "rec_enc_level0_conv0"
  type: "Convolution"
  bottom: "rec"
  top: "rec_enc_level0_conv0"
  convolution_param {
    num_output: 32
    pad: 1
    kernel_size: 3
    weight_filler {
      type: "xavier"
    }
  }
}
layer {
  name: "rec_enc_level0_conv0_relu"
  type: "ReLU"
  bottom: "rec_enc_level0_conv0"
  top: "rec_enc_level0_conv0"
  relu_param {
    negative_slope: 0.10000000149011612
  }
}
layer {
  name: "rec_enc_level0_conv1"
  type: "Convolution"
  bottom: "rec_enc_level0_conv0"
  top: "rec_enc_level0_conv1"
  convolution_param {
    num_output: 32
    pad: 1
    kernel_size: 3
    weight_filler {
      type: "xavier"
    }
  }
}
layer {
  name: "rec_enc_level0_conv1_relu"
  type: "ReLU"
  bottom: "rec_enc_level0_conv1"
  top: "rec_enc_level0_conv1"
  relu_param {
    negative_slope: 0.10000000149011612
  }
}
layer {
  name: "rec_enc_level0_conv2"
  type: "Convolution"
  bottom: "rec_enc_level0_conv1"
  top: "rec_enc_level0_conv2"
  convolution_param {
    num_output: 32
    pad: 1
    kernel_size: 3
    weight_filler {
      type: "xavier"
    }
  }
}
layer {
  name: "rec_enc_level0_conv2_relu"
  type: "ReLU"
  bottom: "rec_enc_level0_conv2"
  top: "rec_enc_level0_conv2"
  relu_param {
    negative_slope: 0.10000000149011612
  }
}
layer {
  name: "rec_enc_level1_pool"
  type: "Pooling"
  bottom: "rec_enc_level0_conv2"
  top: "rec_enc_level1_pool"
  pooling_param {
    pool: AVE
    kernel_size: 2
    stride: 2
  }
}
layer {
  name: "rec_enc_level1_conv0"
  type: "Convolution"
  bottom: "rec_enc_level1_pool"
  top: "rec_enc_level1_conv0"
  convolution_param {
    num_output: 64
    pad: 1
    kernel_size: 3
    weight_filler {
      type: "xavier"
    }
  }
}
layer {
  name: "rec_enc_level1_conv0_relu"
  type: "ReLU"
  bottom: "rec_enc_level1_conv0"
  top: "rec_enc_level1_conv0"
  relu_param {
    negative_slope: 0.10000000149011612
  }
}
layer {
  name: "rec_enc_level1_conv1"
  type: "Convolution"
  bottom: "rec_enc_level1_conv0"
  top: "rec_enc_level1_conv1"
  convolution_param {
    num_output: 64
    pad: 1
    kernel_size: 3
    weight_filler {
      type: "xavier"
    }
  }
}
layer {
  name: "rec_enc_level1_conv1_relu"
  type: "ReLU"
  bottom: "rec_enc_level1_conv1"
  top: "rec_enc_level1_conv1"
  relu_param {
    negative_slope: 0.10000000149011612
  }
}
layer {
  name: "rec_enc_level1_conv2"
  type: "Convolution"
  bottom: "rec_enc_level1_conv1"
  top: "rec_enc_level1_conv2"
  convolution_param {
    num_output: 64
    pad: 1
    kernel_size: 3
    weight_filler {
      type: "xavier"
    }
  }
}
layer {
  name: "rec_enc_level1_conv2_relu"
  type: "ReLU"
  bottom: "rec_enc_level1_conv2"
  top: "rec_enc_level1_conv2"
  relu_param {
    negative_slope: 0.10000000149011612
  }
}
layer {
  name: "rec_enc_level2_pool"
  type: "Pooling"
  bottom: "rec_enc_level1_conv2"
  top: "rec_enc_level2_pool"
  pooling_param {
    pool: AVE
    kernel_size: 2
    stride: 2
  }
}
layer {
  name: "rec_enc_level2_conv0"
  type: "Convolution"
  bottom: "rec_enc_level2_pool"
  top: "rec_enc_level2_conv0"
  convolution_param {
    num_output: 128
    pad: 1
    kernel_size: 3
    weight_filler {
      type: "xavier"
    }
  }
}
layer {
  name: "rec_enc_level2_conv0_relu"
  type: "ReLU"
  bottom: "rec_enc_level2_conv0"
  top: "rec_enc_level2_conv0"
  relu_param {
    negative_slope: 0.10000000149011612
  }
}
layer {
  name: "rec_enc_level2_conv1"
  type: "Convolution"
  bottom: "rec_enc_level2_conv0"
  top: "rec_enc_level2_conv1"
  convolution_param {
    num_output: 128
    pad: 1
    kernel_size: 3
    weight_filler {
      type: "xavier"
    }
  }
}
layer {
  name: "rec_enc_level2_conv1_relu"
  type: "ReLU"
  bottom: "rec_enc_level2_conv1"
  top: "rec_enc_level2_conv1"
  relu_param {
    negative_slope: 0.10000000149011612
  }
}
layer {
  name: "rec_enc_level2_conv2"
  type: "Convolution"
  bottom: "rec_enc_level2_conv1"
  top: "rec_enc_level2_conv2"
  convolution_param {
    num_output: 128
    pad: 1
    kernel_size: 3
    weight_filler {
      type: "xavier"
    }
  }
}
layer {
  name: "rec_enc_level2_conv2_relu"
  type: "ReLU"
  bottom: "rec_enc_level2_conv2"
  top: "rec_enc_level2_conv2"
  relu_param {
    negative_slope: 0.10000000149011612
  }
}
layer {
  name: "rec_enc_level3_pool"
  type: "Pooling"
  bottom: "rec_enc_level2_conv2"
  top: "rec_enc_level3_pool"
  pooling_param {
    pool: AVE
    kernel_size: 2
    stride: 2
  }
}
layer {
  name: "rec_enc_level3_conv0"
  type: "Convolution"
  bottom: "rec_enc_level3_pool"
  top: "rec_enc_level3_conv0"
  convolution_param {
    num_output: 256
    pad: 1
    kernel_size: 3
    weight_filler {
      type: "xavier"
    }
  }
}
layer {
  name: "rec_enc_level3_conv0_relu"
  type: "ReLU"
  bottom: "rec_enc_level3_conv0"
  top: "rec_enc_level3_conv0"
  relu_param {
    negative_slope: 0.10000000149011612
  }
}
layer {
  name: "rec_enc_level3_conv1"
  type: "Convolution"
  bottom: "rec_enc_level3_conv0"
  top: "rec_enc_level3_conv1"
  convolution_param {
    num_output: 256
    pad: 1
    kernel_size: 3
    weight_filler {
      type: "xavier"
    }
  }
}
layer {
  name: "rec_enc_level3_conv1_relu"
  type: "ReLU"
  bottom: "rec_enc_level3_conv1"
  top: "rec_enc_level3_conv1"
  relu_param {
    negative_slope: 0.10000000149011612
  }
}
layer {
  name: "rec_enc_level3_conv2"
  type: "Convolution"
  bottom: "rec_enc_level3_conv1"
  top: "rec_enc_level3_conv2"
  convolution_param {
    num_output: 256
    pad: 1
    kernel_size: 3
    weight_filler {
      type: "xavier"
    }
  }
}
layer {
  name: "rec_enc_level3_conv2_relu"
  type: "ReLU"
  bottom: "rec_enc_level3_conv2"
  top: "rec_enc_level3_conv2"
  relu_param {
    negative_slope: 0.10000000149011612
  }
}
layer {
  name: "rec_latent_fc"
  type: "InnerProduct"
  bottom: "rec_enc_level3_conv2"
  top: "rec_latent_fc"
  inner_product_param {
    num_output: 1024
    weight_filler {
      type: "xavier"
    }
  }
}
layer {
  name: "lig_enc_level0_conv0"
  type: "Convolution"
  bottom: "lig"
  top: "lig_enc_level0_conv0"
  convolution_param {
    num_output: 32
    pad: 1
    kernel_size: 3
    weight_filler {
      type: "xavier"
    }
  }
}
layer {
  name: "lig_enc_level0_conv0_relu"
  type: "ReLU"
  bottom: "lig_enc_level0_conv0"
  top: "lig_enc_level0_conv0"
  relu_param {
    negative_slope: 0.10000000149011612
  }
}
layer {
  name: "lig_enc_level0_conv1"
  type: "Convolution"
  bottom: "lig_enc_level0_conv0"
  top: "lig_enc_level0_conv1"
  convolution_param {
    num_output: 32
    pad: 1
    kernel_size: 3
    weight_filler {
      type: "xavier"
    }
  }
}
layer {
  name: "lig_enc_level0_conv1_relu"
  type: "ReLU"
  bottom: "lig_enc_level0_conv1"
  top: "lig_enc_level0_conv1"
  relu_param {
    negative_slope: 0.10000000149011612
  }
}
layer {
  name: "lig_enc_level0_conv2"
  type: "Convolution"
  bottom: "lig_enc_level0_conv1"
  top: "lig_enc_level0_conv2"
  convolution_param {
    num_output: 32
    pad: 1
    kernel_size: 3
    weight_filler {
      type: "xavier"
    }
  }
}
layer {
  name: "lig_enc_level0_conv2_relu"
  type: "ReLU"
  bottom: "lig_enc_level0_conv2"
  top: "lig_enc_level0_conv2"
  relu_param {
    negative_slope: 0.10000000149011612
  }
}
layer {
  name: "lig_enc_level1_pool"
  type: "Pooling"
  bottom: "lig_enc_level0_conv2"
  top: "lig_enc_level1_pool"
  pooling_param {
    pool: AVE
    kernel_size: 2
    stride: 2
  }
}
layer {
  name: "lig_enc_level1_conv0"
  type: "Convolution"
  bottom: "lig_enc_level1_pool"
  top: "lig_enc_level1_conv0"
  convolution_param {
    num_output: 64
    pad: 1
    kernel_size: 3
    weight_filler {
      type: "xavier"
    }
  }
}
layer {
  name: "lig_enc_level1_conv0_relu"
  type: "ReLU"
  bottom: "lig_enc_level1_conv0"
  top: "lig_enc_level1_conv0"
  relu_param {
    negative_slope: 0.10000000149011612
  }
}
layer {
  name: "lig_enc_level1_conv1"
  type: "Convolution"
  bottom: "lig_enc_level1_conv0"
  top: "lig_enc_level1_conv1"
  convolution_param {
    num_output: 64
    pad: 1
    kernel_size: 3
    weight_filler {
      type: "xavier"
    }
  }
}
layer {
  name: "lig_enc_level1_conv1_relu"
  type: "ReLU"
  bottom: "lig_enc_level1_conv1"
  top: "lig_enc_level1_conv1"
  relu_param {
    negative_slope: 0.10000000149011612
  }
}
layer {
  name: "lig_enc_level1_conv2"
  type: "Convolution"
  bottom: "lig_enc_level1_conv1"
  top: "lig_enc_level1_conv2"
  convolution_param {
    num_output: 64
    pad: 1
    kernel_size: 3
    weight_filler {
      type: "xavier"
    }
  }
}
layer {
  name: "lig_enc_level1_conv2_relu"
  type: "ReLU"
  bottom: "lig_enc_level1_conv2"
  top: "lig_enc_level1_conv2"
  relu_param {
    negative_slope: 0.10000000149011612
  }
}
layer {
  name: "lig_enc_level2_pool"
  type: "Pooling"
  bottom: "lig_enc_level1_conv2"
  top: "lig_enc_level2_pool"
  pooling_param {
    pool: AVE
    kernel_size: 2
    stride: 2
  }
}
layer {
  name: "lig_enc_level2_conv0"
  type: "Convolution"
  bottom: "lig_enc_level2_pool"
  top: "lig_enc_level2_conv0"
  convolution_param {
    num_output: 128
    pad: 1
    kernel_size: 3
    weight_filler {
      type: "xavier"
    }
  }
}
layer {
  name: "lig_enc_level2_conv0_relu"
  type: "ReLU"
  bottom: "lig_enc_level2_conv0"
  top: "lig_enc_level2_conv0"
  relu_param {
    negative_slope: 0.10000000149011612
  }
}
layer {
  name: "lig_enc_level2_conv1"
  type: "Convolution"
  bottom: "lig_enc_level2_conv0"
  top: "lig_enc_level2_conv1"
  convolution_param {
    num_output: 128
    pad: 1
    kernel_size: 3
    weight_filler {
      type: "xavier"
    }
  }
}
layer {
  name: "lig_enc_level2_conv1_relu"
  type: "ReLU"
  bottom: "lig_enc_level2_conv1"
  top: "lig_enc_level2_conv1"
  relu_param {
    negative_slope: 0.10000000149011612
  }
}
layer {
  name: "lig_enc_level2_conv2"
  type: "Convolution"
  bottom: "lig_enc_level2_conv1"
  top: "lig_enc_level2_conv2"
  convolution_param {
    num_output: 128
    pad: 1
    kernel_size: 3
    weight_filler {
      type: "xavier"
    }
  }
}
layer {
  name: "lig_enc_level2_conv2_relu"
  type: "ReLU"
  bottom: "lig_enc_level2_conv2"
  top: "lig_enc_level2_conv2"
  relu_param {
    negative_slope: 0.10000000149011612
  }
}
layer {
  name: "lig_enc_level3_pool"
  type: "Pooling"
  bottom: "lig_enc_level2_conv2"
  top: "lig_enc_level3_pool"
  pooling_param {
    pool: AVE
    kernel_size: 2
    stride: 2
  }
}
layer {
  name: "lig_enc_level3_conv0"
  type: "Convolution"
  bottom: "lig_enc_level3_pool"
  top: "lig_enc_level3_conv0"
  convolution_param {
    num_output: 256
    pad: 1
    kernel_size: 3
    weight_filler {
      type: "xavier"
    }
  }
}
layer {
  name: "lig_enc_level3_conv0_relu"
  type: "ReLU"
  bottom: "lig_enc_level3_conv0"
  top: "lig_enc_level3_conv0"
  relu_param {
    negative_slope: 0.10000000149011612
  }
}
layer {
  name: "lig_enc_level3_conv1"
  type: "Convolution"
  bottom: "lig_enc_level3_conv0"
  top: "lig_enc_level3_conv1"
  convolution_param {
    num_output: 256
    pad: 1
    kernel_size: 3
    weight_filler {
      type: "xavier"
    }
  }
}
layer {
  name: "lig_enc_level3_conv1_relu"
  type: "ReLU"
  bottom: "lig_enc_level3_conv1"
  top: "lig_enc_level3_conv1"
  relu_param {
    negative_slope: 0.10000000149011612
  }
}
layer {
  name: "lig_enc_level3_conv2"
  type: "Convolution"
  bottom: "lig_enc_level3_conv1"
  top: "lig_enc_level3_conv2"
  convolution_param {
    num_output: 256
    pad: 1
    kernel_size: 3
    weight_filler {
      type: "xavier"
    }
  }
}
layer {
  name: "lig_enc_level3_conv2_relu"
  type: "ReLU"
  bottom: "lig_enc_level3_conv2"
  top: "lig_enc_level3_conv2"
  relu_param {
    negative_slope: 0.10000000149011612
  }
}
layer {
  name: "lig_latent_mean"
  type: "InnerProduct"
  bottom: "lig_enc_level3_conv2"
  top: "lig_latent_mean"
  inner_product_param {
    num_output: 1024
    weight_filler {
      type: "xavier"
    }
  }
}
layer {
  name: "lig_latent_log_std"
  type: "InnerProduct"
  bottom: "lig_enc_level3_conv2"
  top: "lig_latent_log_std"
  inner_product_param {
    num_output: 1024
    weight_filler {
      type: "xavier"
    }
  }
}
layer {
  name: "lig_latent_std"
  type: "Exp"
  bottom: "lig_latent_log_std"
  top: "lig_latent_std"
}
layer {
  name: "lig_latent_noise"
  type: "DummyData"
  top: "lig_latent_noise"
  dummy_data_param {
    data_filler {
      type: "gaussian"
    }
    shape {
      dim: 16
      dim: 1024
    }
  }
}
layer {
  name: "lig_latent_std_noise"
  type: "Eltwise"
  bottom: "lig_latent_noise"
  bottom: "lig_latent_std"
  top: "lig_latent_std_noise"
  eltwise_param {
    operation: PROD
  }
}
layer {
  name: "lig_latent_sample"
  type: "Eltwise"
  bottom: "lig_latent_std_noise"
  bottom: "lig_latent_mean"
  top: "lig_latent_sample"
  eltwise_param {
    operation: SUM
  }
}
layer {
  name: "lig_latent_mean2"
  type: "Eltwise"
  bottom: "lig_latent_mean"
  bottom: "lig_latent_mean"
  top: "lig_latent_mean2"
  eltwise_param {
    operation: PROD
  }
}
layer {
  name: "lig_latent_var"
  type: "Eltwise"
  bottom: "lig_latent_std"
  bottom: "lig_latent_std"
  top: "lig_latent_var"
  eltwise_param {
    operation: PROD
  }
}
layer {
  name: "lig_latent_one"
  type: "DummyData"
  top: "lig_latent_one"
  dummy_data_param {
    data_filler {
      type: "constant"
      value: 1.0
    }
    shape {
      dim: 16
      dim: 1024
    }
  }
}
layer {
  name: "lig_latent_kldiv_term_sum"
  type: "Eltwise"
  bottom: "lig_latent_one"
  bottom: "lig_latent_log_std"
  bottom: "lig_latent_mean2"
  bottom: "lig_latent_var"
  top: "lig_latent_kldiv_term_sum"
  eltwise_param {
    operation: SUM
    coeff: -0.5
    coeff: -1.0
    coeff: 0.5
    coeff: 0.5
  }
}
layer {
  name: "{}_latent_kldiv_batch_sum"
  type: "Reduction"
  bottom: "lig_latent_kldiv_term_sum"
  top: "{}_latent_kldiv_batch_sum"
  reduction_param {
    operation: SUM
  }
}
layer {
  name: "kldiv_loss"
  type: "Power"
  bottom: "{}_latent_kldiv_batch_sum"
  top: "kldiv_loss"
  loss_weight: 1.0
  power_param {
    scale: 0.0625
  }
}
layer {
  name: "latent_concat"
  type: "Concat"
  bottom: "rec_latent_fc"
  bottom: "lig_latent_sample"
  top: "latent_concat"
  concat_param {
    axis: 1
  }
}
layer {
  name: "lig_dec_fc"
  type: "InnerProduct"
  bottom: "latent_concat"
  top: "lig_dec_fc"
  inner_product_param {
    num_output: 55296
    weight_filler {
      type: "xavier"
    }
  }
}
layer {
  name: "lig_dec_fc_relu"
  type: "ReLU"
  bottom: "lig_dec_fc"
  top: "lig_dec_fc"
  relu_param {
    negative_slope: 0.10000000149011612
  }
}
layer {
  name: "lig_dec_fc_reshape"
  type: "Reshape"
  bottom: "lig_dec_fc"
  top: "lig_dec_fc_reshape"
  reshape_param {
    shape {
      dim: 16
      dim: 256
      dim: 6
      dim: 6
      dim: 6
    }
  }
}
layer {
  name: "lig_dec_level3_deconv0"
  type: "Deconvolution"
  bottom: "lig_dec_fc_reshape"
  top: "lig_dec_level3_deconv0"
  convolution_param {
    num_output: 256
    pad: 1
    kernel_size: 3
    weight_filler {
      type: "xavier"
    }
  }
}
layer {
  name: "lig_dec_level3_deconv0_relu"
  type: "ReLU"
  bottom: "lig_dec_level3_deconv0"
  top: "lig_dec_level3_deconv0"
  relu_param {
    negative_slope: 0.10000000149011612
  }
}
layer {
  name: "lig_dec_level3_deconv1"
  type: "Deconvolution"
  bottom: "lig_dec_level3_deconv0"
  top: "lig_dec_level3_deconv1"
  convolution_param {
    num_output: 256
    pad: 1
    kernel_size: 3
    weight_filler {
      type: "xavier"
    }
  }
}
layer {
  name: "lig_dec_level3_deconv1_relu"
  type: "ReLU"
  bottom: "lig_dec_level3_deconv1"
  top: "lig_dec_level3_deconv1"
  relu_param {
    negative_slope: 0.10000000149011612
  }
}
layer {
  name: "lig_dec_level3_deconv2"
  type: "Deconvolution"
  bottom: "lig_dec_level3_deconv1"
  top: "lig_dec_level3_deconv2"
  convolution_param {
    num_output: 256
    pad: 1
    kernel_size: 3
    weight_filler {
      type: "xavier"
    }
  }
}
layer {
  name: "lig_dec_level3_deconv2_relu"
  type: "ReLU"
  bottom: "lig_dec_level3_deconv2"
  top: "lig_dec_level3_deconv2"
  relu_param {
    negative_slope: 0.10000000149011612
  }
}
layer {
  name: "lig_dec_level2_unpool"
  type: "Deconvolution"
  bottom: "lig_dec_level3_deconv2"
  top: "lig_dec_level2_unpool"
  param {
    lr_mult: 0.0
    decay_mult: 0.0
  }
  convolution_param {
    num_output: 256
    bias_term: false
    kernel_size: 2
    group: 256
    stride: 2
    weight_filler {
      type: "constant"
      value: 1.0
    }
    engine: CAFFE
  }
}
layer {
  name: "lig_dec_level2_deconv0"
  type: "Deconvolution"
  bottom: "lig_dec_level2_unpool"
  top: "lig_dec_level2_deconv0"
  convolution_param {
    num_output: 128
    pad: 1
    kernel_size: 3
    weight_filler {
      type: "xavier"
    }
  }
}
layer {
  name: "lig_dec_level2_deconv0_relu"
  type: "ReLU"
  bottom: "lig_dec_level2_deconv0"
  top: "lig_dec_level2_deconv0"
  relu_param {
    negative_slope: 0.10000000149011612
  }
}
layer {
  name: "lig_dec_level2_deconv1"
  type: "Deconvolution"
  bottom: "lig_dec_level2_deconv0"
  top: "lig_dec_level2_deconv1"
  convolution_param {
    num_output: 128
    pad: 1
    kernel_size: 3
    weight_filler {
      type: "xavier"
    }
  }
}
layer {
  name: "lig_dec_level2_deconv1_relu"
  type: "ReLU"
  bottom: "lig_dec_level2_deconv1"
  top: "lig_dec_level2_deconv1"
  relu_param {
    negative_slope: 0.10000000149011612
  }
}
layer {
  name: "lig_dec_level2_deconv2"
  type: "Deconvolution"
  bottom: "lig_dec_level2_deconv1"
  top: "lig_dec_level2_deconv2"
  convolution_param {
    num_output: 128
    pad: 1
    kernel_size: 3
    weight_filler {
      type: "xavier"
    }
  }
}
layer {
  name: "lig_dec_level2_deconv2_relu"
  type: "ReLU"
  bottom: "lig_dec_level2_deconv2"
  top: "lig_dec_level2_deconv2"
  relu_param {
    negative_slope: 0.10000000149011612
  }
}
layer {
  name: "lig_dec_level1_unpool"
  type: "Deconvolution"
  bottom: "lig_dec_level2_deconv2"
  top: "lig_dec_level1_unpool"
  param {
    lr_mult: 0.0
    decay_mult: 0.0
  }
  convolution_param {
    num_output: 128
    bias_term: false
    kernel_size: 2
    group: 128
    stride: 2
    weight_filler {
      type: "constant"
      value: 1.0
    }
    engine: CAFFE
  }
}
layer {
  name: "lig_dec_level1_deconv0"
  type: "Deconvolution"
  bottom: "lig_dec_level1_unpool"
  top: "lig_dec_level1_deconv0"
  convolution_param {
    num_output: 64
    pad: 1
    kernel_size: 3
    weight_filler {
      type: "xavier"
    }
  }
}
layer {
  name: "lig_dec_level1_deconv0_relu"
  type: "ReLU"
  bottom: "lig_dec_level1_deconv0"
  top: "lig_dec_level1_deconv0"
  relu_param {
    negative_slope: 0.10000000149011612
  }
}
layer {
  name: "lig_dec_level1_deconv1"
  type: "Deconvolution"
  bottom: "lig_dec_level1_deconv0"
  top: "lig_dec_level1_deconv1"
  convolution_param {
    num_output: 64
    pad: 1
    kernel_size: 3
    weight_filler {
      type: "xavier"
    }
  }
}
layer {
  name: "lig_dec_level1_deconv1_relu"
  type: "ReLU"
  bottom: "lig_dec_level1_deconv1"
  top: "lig_dec_level1_deconv1"
  relu_param {
    negative_slope: 0.10000000149011612
  }
}
layer {
  name: "lig_dec_level1_deconv2"
  type: "Deconvolution"
  bottom: "lig_dec_level1_deconv1"
  top: "lig_dec_level1_deconv2"
  convolution_param {
    num_output: 64
    pad: 1
    kernel_size: 3
    weight_filler {
      type: "xavier"
    }
  }
}
layer {
  name: "lig_dec_level1_deconv2_relu"
  type: "ReLU"
  bottom: "lig_dec_level1_deconv2"
  top: "lig_dec_level1_deconv2"
  relu_param {
    negative_slope: 0.10000000149011612
  }
}
layer {
  name: "lig_dec_level0_unpool"
  type: "Deconvolution"
  bottom: "lig_dec_level1_deconv2"
  top: "lig_dec_level0_unpool"
  param {
    lr_mult: 0.0
    decay_mult: 0.0
  }
  convolution_param {
    num_output: 64
    bias_term: false
    kernel_size: 2
    group: 64
    stride: 2
    weight_filler {
      type: "constant"
      value: 1.0
    }
    engine: CAFFE
  }
}
layer {
  name: "lig_dec_level0_deconv0"
  type: "Deconvolution"
  bottom: "lig_dec_level0_unpool"
  top: "lig_dec_level0_deconv0"
  convolution_param {
    num_output: 32
    pad: 1
    kernel_size: 3
    weight_filler {
      type: "xavier"
    }
  }
}
layer {
  name: "lig_dec_level0_deconv0_relu"
  type: "ReLU"
  bottom: "lig_dec_level0_deconv0"
  top: "lig_dec_level0_deconv0"
  relu_param {
    negative_slope: 0.10000000149011612
  }
}
layer {
  name: "lig_dec_level0_deconv1"
  type: "Deconvolution"
  bottom: "lig_dec_level0_deconv0"
  top: "lig_dec_level0_deconv1"
  convolution_param {
    num_output: 32
    pad: 1
    kernel_size: 3
    weight_filler {
      type: "xavier"
    }
  }
}
layer {
  name: "lig_dec_level0_deconv1_relu"
  type: "ReLU"
  bottom: "lig_dec_level0_deconv1"
  top: "lig_dec_level0_deconv1"
  relu_param {
    negative_slope: 0.10000000149011612
  }
}
layer {
  name: "lig_dec_level0_deconv2"
  type: "Deconvolution"
  bottom: "lig_dec_level0_deconv1"
  top: "lig_dec_level0_deconv2"
  convolution_param {
    num_output: 19
    pad: 1
    kernel_size: 3
    weight_filler {
      type: "xavier"
    }
  }
}
layer {
  name: "lig_dec_level0_deconv2_relu"
  type: "ReLU"
  bottom: "lig_dec_level0_deconv2"
  top: "lig_dec_level0_deconv2"
  relu_param {
    negative_slope: 0.10000000149011612
  }
}
layer {
  name: "lig_gen"
  type: "Power"
  bottom: "lig_dec_level0_deconv2"
  top: "lig_gen"
}
layer {
  name: "diff"
  type: "Eltwise"
  bottom: "lig_dec_level0_deconv2"
  bottom: "lig"
  top: "diff"
  eltwise_param {
    operation: SUM
    coeff: 1.0
    coeff: -1.0
  }
}
layer {
  name: "abs_sum"
  type: "Reduction"
  bottom: "diff"
  top: "abs_sum"
  reduction_param {
    operation: ASUM
  }
}
layer {
  name: "L1_loss"
  type: "Power"
  bottom: "abs_sum"
  top: "L1_loss"
  loss_weight: 1.0
  power_param {
    scale: 0.0625
  }
}


the disc_param.model:
# encode_type = 'disc'
# rec_map = 'my_rec_map'
# lig_map = 'my_lig_map'
# data_dim = 48
# n_levels = 3
# conv_per_level = 1
# arch_options = 'l'
# n_filters = 16
# width_factor = 2
# n_latent = 1
# loss_types = 'w'
layer {
  name: "rec"
  type: "Input"
  top: "rec"
  input_param {
    shape {
      dim: 16
      dim: 16
      dim: 48
      dim: 48
      dim: 48
    }
  }
}
layer {
  name: "lig"
  type: "Input"
  top: "lig"
  input_param {
    shape {
      dim: 16
      dim: 19
      dim: 48
      dim: 48
      dim: 48
    }
  }
}
layer {
  name: "data"
  type: "Concat"
  bottom: "rec"
  bottom: "lig"
  top: "data"
  concat_param {
    axis: 1
  }
}
layer {
  name: "label"
  type: "Input"
  top: "label"
  input_param {
    shape {
      dim: 16
      dim: 1
    }
  }
}
layer {
  name: "data_enc_level0_conv0"
  type: "Convolution"
  bottom: "data"
  top: "data_enc_level0_conv0"
  convolution_param {
    num_output: 16
    pad: 1
    kernel_size: 3
    weight_filler {
      type: "xavier"
    }
  }
}
layer {
  name: "data_enc_level0_conv0_relu"
  type: "ReLU"
  bottom: "data_enc_level0_conv0"
  top: "data_enc_level0_conv0"
  relu_param {
    negative_slope: 0.10000000149011612
  }
}
layer {
  name: "data_enc_level1_pool"
  type: "Pooling"
  bottom: "data_enc_level0_conv0"
  top: "data_enc_level1_pool"
  pooling_param {
    pool: AVE
    kernel_size: 2
    stride: 2
  }
}
layer {
  name: "data_enc_level1_conv0"
  type: "Convolution"
  bottom: "data_enc_level1_pool"
  top: "data_enc_level1_conv0"
  convolution_param {
    num_output: 32
    pad: 1
    kernel_size: 3
    weight_filler {
      type: "xavier"
    }
  }
}
layer {
  name: "data_enc_level1_conv0_relu"
  type: "ReLU"
  bottom: "data_enc_level1_conv0"
  top: "data_enc_level1_conv0"
  relu_param {
    negative_slope: 0.10000000149011612
  }
}
layer {
  name: "data_enc_level2_pool"
  type: "Pooling"
  bottom: "data_enc_level1_conv0"
  top: "data_enc_level2_pool"
  pooling_param {
    pool: AVE
    kernel_size: 2
    stride: 2
  }
}
layer {
  name: "data_enc_level2_conv0"
  type: "Convolution"
  bottom: "data_enc_level2_pool"
  top: "data_enc_level2_conv0"
  convolution_param {
    num_output: 64
    pad: 1
    kernel_size: 3
    weight_filler {
      type: "xavier"
    }
  }
}
layer {
  name: "data_enc_level2_conv0_relu"
  type: "ReLU"
  bottom: "data_enc_level2_conv0"
  top: "data_enc_level2_conv0"
  relu_param {
    negative_slope: 0.10000000149011612
  }
}
layer {
  name: "data_latent_fc"
  type: "InnerProduct"
  bottom: "data_enc_level2_conv0"
  top: "data_latent_fc"
  inner_product_param {
    num_output: 1
    weight_filler {
      type: "xavier"
    }
  }
}
layer {
  name: "output"
  type: "Power"
  bottom: "data_latent_fc"
  top: "output"
}
layer {
  name: "wass_sign"
  type: "Power"
  bottom: "label"
  top: "wass_sign"
  power_param {
    scale: -2.0
    shift: 1.0
  }
}
layer {
  name: "wass_prod"
  type: "Eltwise"
  bottom: "wass_sign"
  bottom: "data_latent_fc"
  top: "wass_prod"
  eltwise_param {
    operation: PROD
  }
}
layer {
  name: "wass_loss"
  type: "Reduction"
  bottom: "wass_prod"
  top: "wass_loss"
  loss_weight: 1.0
  reduction_param {
    operation: MEAN
  }
}

Please help check. i am also wondering how much memory used when training one a 1000-data set.
