### ISSUE TITLE
Sulfonyl group

### ISSUE THREAD

**Issue by RMeli** [mattragoza/liGAN#15]
I've noticed that when the seed molecule contains a sulfonyl group, the generated molecule (with variability factor `1.0`) often contain a sulfur atoms bound to two oxygen atoms with a single bond instead of a double bond and they end up being negatively charged. This causes the molecule to break during optimization with UFF (there is not compensating +2 charge on sulfur).

I haven't been able to track down this problem so far, but I think it could be beneficial to add additional sanitization steps to generated molecules (standardization and of functional groups and neutralization of the whole molecule)?

**Comment by mattragoza** [comment]
Thanks for bringing this to my attention, do you have a simple test case that reproduces the problem (with a particular model/set of weights)?

**Comment by mattragoza** [comment]
I've just pushed a commit (0a252d0) to master that adds a very simple check for potential sulfonyl groups when deciding on the maximum permitted valence.
