### ISSUE TITLE
Can not run `generate.py` to generate molecules.

### ISSUE THREAD

**Issue by MhDang** [mattragoza/liGAN#16]
Hi,

I'm trying to use your models to generate some molecules, however when I run `generate.py` as shown in the README.md, there are errors related to 

```
from SA_Score import sascorer
from NP_Score import npscorer
```

There seems no such modules, or maybe some files are missing?

I also found there is a `refactor` branch, are there some `generate.py` like scripts in this branch? Or there are only training scripts. 

I would greatly appreciate it if you would provide some clues or solutions of my question.

**Comment by MhDang** [comment]
It seems i need to manually add them from rdkit.

I will close this issue

**Comment by mattragoza** [comment]
To follow-up on this issue, you are correct that the rdkit/Contrib folder previously had to be added manually. I have pushed a commit (7d760bde) that adds the location to the path automatically in generate.py.
