### ISSUE TITLE
SA_Score and NP_Score

### ISSUE THREAD

**Issue by loverring** [mattragoza/liGAN#17]
I found 
"from SA_Score import sascorer
from NP_Score import npscorer"
in generate.py. But I failed to find where the declaration of these functions are. Could you provide them?

**Comment by mattragoza** [comment]
These are from the RDKit contrib dir (rdkit/Contrib), which needs to be manually appended to the PYTHONPATH. I've just added a commit (7d760bde) that does this automatically in generate.py.
