### ISSUE TITLE
Is the generated molecules really conditional on the receptor?

### ISSUE THREAD

**Issue by yangxiufengsia** [mattragoza/liGAN#19]
Hi, I have questions for your paper: Generating 3D Molecular Structures Conditional on a
Receptor Binding Site with Deep Generative Models.

1. You include binding pocket in both encoder and decoder of VAE, but is it possible that finally VAE learns to ignore the features of binding pocket? Since your final output is try to reconstruct from input ligand only. 
2. I noticed you provided some experiments to show the different perfornace of  "with receptor" and "without receptor" using prior sampling only,  as shown in figure 7. But did you check the different performance on posterior sampling? I mean what if input a unpaired binding pocket and ligand? does it reconstruct the input ligand no matter which binding pockets you input to vae?

Looking forward to your reply. Thanks.

**Comment by mattragoza** [comment]
Apologies for the delay in responding, we are working on a draft of an updated manuscript on improvements to this work. One of the key dimensions we are working to improve on is the degree of receptor conditionality of the generated ligands, especially for prior ligands. Given that the prior ligands tended to be smaller but have higher Vina energy and lower CNN affinity, it is fair to say that they had less favorable receptor interactions on average, which would indicate at the very least that the model is not as receptor-conditional as we would like. We have not performed the evaluation you mentioned yet but we will surely include it in our updated manuscript.

**Comment by yangxiufengsia** [comment]
Thanks a lot.  That would be very interesting to read your updated paper.
