### ISSUE TITLE
model cannot be trained

### ISSUE THREAD

**Issue by yuanqidu** [mattragoza/LiGAN#28]
When I attempted to train the code with train.py and the provided simple example it2_tt_0_lowrmsd_valid_mols_test0_1000.types and crossdock folder, the model froze in the dataloader next_batch part.

Looking forward to your help!

**Comment by mattragoza** [comment]
The data file that references the structures in the data/crossdock2020/ directory is data/crossdock2020/selected_test_targets.types. This only includes the 10 targets that we selected for test evaluations, so I would not advise training a model on it.

Instructions for downloading the full crossdocked dataset can be found here: 
https://github.com/gnina/models/tree/master/data/CrossDocked2020

If you would like to train a model from scratch using the full CrossDocked2020 data set, I can make the required data files (.types files) available.

**Comment by yuanqidu** [comment]
Thanks for your help! Yes, I did try to use crossdock for training, but the code just froze at next_batch under libmolgrid library.

**Comment by mattragoza** [comment]
Can you provide your conda environment?

**Comment by yuanqidu** [comment]
examples = self.ex_provider.next_batch(self.batch_size)
ValueError: Vector typer used with gninatypes files

**Comment by mattragoza** [comment]
How did you install openbabel and libmolgrid?

**Comment by RMeli** [comment]
@yuanqidu posted this error, before editing the message above:
```
examples = self.ex_provider.next_batch(self.batch_size)
ValueError: Vector typer used with gninatypes files
```
Isn't this related to a mismatch between the types contained in the `.gninatypes` files for the CrossDocked2020 (original typing scheme used in GNINA) and the new typing scheme that the refactored version of liGAN uses?

**Comment by mattragoza** [comment]
@RMeli Yes, that error message indicates that you are trying to train using gninatypes files or a molcache2 file, which is not compatible with vectorized atom typing that is used by this project. If that's the case, you have to download the full crossdocked2020 dataset (the structure files, not the molcaches) and use that instead. You can reference config/train.config file for how the data paths should be set up.

**Comment by yuanqidu** [comment]
Thanks for the catch... I loaded the wrong package from the crossdock dataset for that run, BUT it was not the main reason, I deleted it because I corrected it very soon. So, it was not the error.

**Comment by mattragoza** [comment]
Those train and test files reference the custom gninatypes format that is not compatible with liGAN. You should use the following train and test files:

http://bits.csb.pitt.edu/files/it2_tt_0_lowrmsd_mols_train0.types
http://bits.csb.pitt.edu/files/it2_tt_0_lowrmsd_mols_test0.types

**Comment by yuanqidu** [comment]
Thanks so much. But it seems the error is still there, when calling next_batch, it froze forever and later the process is killed.
![image](https://user-images.githubusercontent.com/47015173/145662662-f9f34868-c2fa-472c-a9c7-0deed5da16da.png)

**Comment by mattragoza** [comment]
In that case, this is probably due to a mismatch between the conda-installed openbabel and the version used by pip-installed molgrid. This is a [known issue](https://github.com/gnina/libmolgrid/issues/62) that is resolvable by building libmolgrid from source using the version of openbabel that you have installed on your system.

**Comment by yuanqidu** [comment]
When I tried to manually build the libmolgrid, I could not use the command apt install libeigen3-dev libboost-all-dev since I am on centos 7. What openbabel version is compatible with the package? May I re-install the openbabel instead of the molgrid package?

**Comment by yuanqidu** [comment]
Finally, after manually installing libmolgrid, I solved the problem.

But I have one more question, the files mentioned in the given types for training are .sdf.gz, while in the dataset donwloaded are gninatypes, there is a mismatch.

**Comment by mattragoza** [comment]
Great, I'm glad you were able to manually build libmolgrid.

Please follow the steps in the download_data.sh script to download the full crossdocked dataset, which should include .sdf.gz:
```
#!/bin/bash
wget https://bits.csb.pitt.edu/files/crossdock2020/CrossDocked2020_v1.1.tgz -P data/crossdock2020/
tar -C data/crossdock2020/ -xzf data/crossdock2020/CrossDocked2020_v1.1.tgz
wget https://bits.csb.pitt.edu/files/it2_tt_0_lowrmsd_mols_train0.types -P data/crossdock2020/
wget https://bits.csb.pitt.edu/files/it2_tt_0_lowrmsd_mols_test0.types -P data/crossdock2020/
```

**Comment by mattragoza** [comment]
Also note that the types2xyz.py script that David mentioned in the libmolgrid issue you opened will not work for this project, since we use an alternative typing scheme. The gninatypes files contain atoms that already have a different type scheme applied, so there is no way to use them for this project. You will need to download the original molecule files to train a generative model.

**Comment by yuanqidu** [comment]
Thanks, I did download the dataset following the bash script. But in the folder it contains many ginatypes while the code in liGAN asks for sdf. I think there is a mismatch and when I run the code, it reports file cannot be open/found.

![image](https://user-images.githubusercontent.com/47015173/146101004-da031c0c-49f4-4027-8f8f-3d1b792da818.png)

![image](https://user-images.githubusercontent.com/47015173/146101085-b71cec72-5823-426d-95ba-57286448ce3a.png)

**Comment by mattragoza** [comment]
Ah, the problem is that the molecules in the downloaded crossdocked2020 dataset contain multiple poses, but we need them to be split out so that individual poses are in separate files. There is a script to do this but the step is currently missing from the download_data.sh script, my apologies. I will update the script and let you know how to run it ASAP.

**Comment by yuanqidu** [comment]
Yes, thanks, please :)

**Comment by mattragoza** [comment]
The following commands will split out the poses in the sdf.gz files that you need for training:
```
# split multi-pose files into single-pose files
python scripts/split_sdf.py data/crossdock2020/it2_tt_0_lowrmsd_mols_train0.types data/crossdock2020
python scripts/split_sdf.py data/crossdock2020/it2_tt_0_lowrmsd_mols_test0.types data/crossdock2020
```

**Comment by mattragoza** [comment]
Just FYI, there are some issues with the data set that I am working to resolve. The train and test files will have to be updated to remove some bad/missing molecules.

**Comment by yuanqidu** [comment]
Thanks very much for your help!

**Comment by yuanqidu** [comment]
May I just move the missing files from the types file?

**Comment by yuanqidu** [comment]
I have one more question about the method. Did you first extract the pocket from the protein or did you use the full protein and ligand for conditional generation? If you did extract pocket, how did you do so?

**Comment by mattragoza** [comment]
Yes, you can simply remove the missing data rows from the .types files. We provide the full protein as input to conditional generation, but only the binding pocket will fit in the grid bounds. The grid will be centered on the ligand provided to the input encoder, so it is assumed that the input ligand will already be in the binding pocket.

**Comment by mattragoza** [comment]
There are functions to extract pockets for UFF minimization in the binding pocket context (see `liGAN.molecules.get_rd_mol_pocket`), but I would not recommend doing for proteins that are input to the generative model

**Comment by wxfsd** [comment]
Hello, I ran into the same problem. What is your openbabel version? How to install lib manually? @yuanqidu 
Looking forward to your help!

**Comment by mattragoza** [comment]
Hello @yuanqidu @wxfsd, I wanted to update you on this issue as I am actively working to resolve it. The problem is that there is an incompatibility between the conda-installed openbabel and conda/pip-installed molgrid (they are the same binary). I am working on a conda build recipe that will hopefully resolve this issue (https://github.com/mattragoza/conda-molgrid), but it is still under construction. I have provided an environment.yaml file in the conda-molgrid repo that you should be able to use to create a conda environment in which you can successfully build molgrid from source. Please let me know if you run into issues using this conda environment (if you do, please open an issue in the conda-molgrid repo).

**Comment by wxfsd** [comment]
Okay, I'm trying, I will ask on that link (https://github.com/mattragoza/conda-molgrid) if I have any issues. Thank you very much. @mattragoza

**Comment by mattragoza** [comment]
@yuanqidu also I have uploaded new types files that have the problematic poses removed, you can find the the links in the download_data.sh script

**Comment by yuanqidu** [comment]
Thanks! May I ask how many (percentage) problematic files were removed?

Happy new year!

**Comment by mattragoza** [comment]
9 total poses were removed from the data files.
