### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Mingchenchen** [mattragoza/LiGAN#29]
Hi, 

I downloaded the code and try to run generate.py. But got a core dumped error, while importing liGAN. 

Any idea of where the problem should be?

**Comment by mattragoza** [comment]
Can you provide your system and environment information? Specifically, how did you install libmolgrid and openbabel?

**Comment by Mingchenchen** [comment]
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             4.5                       1_gnu    defaults
blas                      1.0                         mkl    defaults
boost                     1.72.0           py37h48f8a5e_1    conda-forge
boost-cpp                 1.72.0               h9d3c048_4    conda-forge
bottleneck                1.3.2            py37heb32a55_1    defaults
brotli                    1.0.9                he6710b0_2    defaults
bzip2                     1.0.8                h7b6447c_0    defaults
ca-certificates           2021.10.8            ha878542_0    conda-forge
cairo                     1.16.0               hf32fb01_1    defaults
certifi                   2021.10.8        py37h89c1867_1    conda-forge
cloudpickle               2.0.0              pyhd3eb1b0_0    defaults
cudatoolkit               10.2.89              hfd86e86_1    defaults
cycler                    0.11.0             pyhd3eb1b0_0    defaults
cytoolz                   0.11.0           py37h7b6447c_0    defaults
dask-core                 2021.10.0          pyhd3eb1b0_0    defaults
fontconfig                2.13.1               h6c09931_0    defaults
fonttools                 4.25.0             pyhd3eb1b0_0    defaults
freetype                  2.11.0               h70c0345_0    defaults
fsspec                    2021.10.1          pyhd3eb1b0_0    defaults
giflib                    5.2.1                h7b6447c_0    defaults
glib                      2.69.1               h5202010_0    defaults
gputil                    1.4.0                    pypi_0    pypi
greenlet                  1.1.1            py37h295c915_0    defaults
icu                       68.1                 h2531618_0    defaults
imageio                   2.9.0              pyhd3eb1b0_0    defaults
importlib-metadata        4.8.2            py37h06a4308_0    defaults
intel-openmp              2021.4.0          h06a4308_3561    defaults
jpeg                      9d                   h7f8727e_0    defaults
kiwisolver                1.3.1            py37h2531618_0    defaults
lcms2                     2.12                 h3be6417_0    defaults
ld_impl_linux-64          2.35.1               h7274673_9    defaults
libffi                    3.3                  he6710b0_2    defaults
libgcc-ng                 9.3.0               h5101ec6_17    defaults
libgfortran-ng            7.5.0               ha8ba4b0_17    defaults
libgfortran4              7.5.0               ha8ba4b0_17    defaults
libgomp                   9.3.0               h5101ec6_17    defaults
libiconv                  1.16                 h516909a_0    conda-forge
libpng                    1.6.37               hbc83047_0    defaults
libstdcxx-ng              9.3.0               hd4cf53a_17    defaults
libtiff                   4.2.0                h85742a9_0    defaults
libuuid                   1.0.3                h7f8727e_2    defaults
libuv                     1.40.0               h7b6447c_0    defaults
libwebp                   1.2.0                h89dd481_0    defaults
libwebp-base              1.2.0                h27cfd23_0    defaults
libxcb                    1.14                 h7b6447c_0    defaults
libxml2                   2.9.12               h72842e0_0    conda-forge
locket                    0.2.1            py37h06a4308_1    defaults
lz4-c                     1.9.3                h295c915_1    defaults
matplotlib-base           3.5.0            py37h3ed280b_0    defaults
mkl                       2021.4.0           h06a4308_640    defaults
mkl-service               2.4.0            py37h7f8727e_0    defaults
mkl_fft                   1.3.1            py37hd3c417c_0    defaults
mkl_random                1.2.2            py37h51133e4_0    defaults
molgrid                   0.0.1                    py37_0    jsunseri
munkres                   1.1.4                      py_0    defaults
ncurses                   6.3                  h7f8727e_2    defaults
networkx                  2.6.3              pyhd3eb1b0_0    defaults
ninja                     1.10.2           py37hd09550d_3    defaults
numexpr                   2.7.3            py37h22e1b3c_1    defaults
numpy                     1.20.3           py37hf144106_0    defaults
numpy-base                1.20.3           py37h74d4b33_0    defaults
olefile                   0.46                     py37_0    defaults
openbabel                 3.1.1            py37h200e996_1    conda-forge
openssl                   1.1.1l               h7f8727e_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
packaging                 21.3               pyhd3eb1b0_0    defaults
pandas                    1.3.3            py37h8c16a72_0    defaults
partd                     1.2.0              pyhd3eb1b0_0    defaults
pcre                      8.45                 h295c915_0    defaults
pillow                    8.4.0            py37h5aabda8_0    defaults
pip                       21.2.2           py37h06a4308_0    defaults
pixman                    0.40.0               h7f8727e_1    defaults
pycairo                   1.20.1           py37hfff247e_0    conda-forge
pynvml                    11.4.1             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.4              pyhd3eb1b0_0    defaults
python                    3.7.11               h12debd9_0    defaults
python-dateutil           2.8.2              pyhd3eb1b0_0    defaults
python_abi                3.7                     2_cp37m    conda-forge
pytorch                   1.9.1           py3.7_cuda10.2_cudnn7.6.5_0    pytorch
pytz                      2021.3             pyhd3eb1b0_0    defaults
pywavelets                1.1.1            py37h7b6447c_2    defaults
pyyaml                    6.0              py37h7f8727e_1    defaults
rdkit                     2020.09.3        py37h400b6df_0    conda-forge
readline                  8.1                  h27cfd23_0    defaults
reportlab                 3.5.68           py37h69800bb_0    conda-forge
scikit-image              0.15.0           py37hb3f55d8_2    conda-forge
scipy                     1.7.1            py37h292c36d_2    defaults
setuptools                58.0.4           py37h06a4308_0    defaults
six                       1.16.0             pyhd3eb1b0_0    defaults
sqlalchemy                1.4.27           py37h7f8727e_0    defaults
sqlite                    3.36.0               hc218d9a_0    defaults
tk                        8.6.11               h1ccaba5_0    defaults
toolz                     0.11.2             pyhd3eb1b0_0    defaults
typing_extensions         3.10.0.2           pyh06a4308_0    defaults
wheel                     0.37.0             pyhd3eb1b0_1    defaults
xz                        5.2.5                h7b6447c_0    defaults
yaml                      0.2.5                h7b6447c_0    defaults
zipp                      3.6.0              pyhd3eb1b0_0    defaults
zlib                      1.2.11               h7b6447c_3    defaults
zstd                      1.4.9                haebb681_0    defaults

**Comment by Mingchenchen** [comment]
Hi I put my conda environment here. Thanks a lot.

**Comment by mattragoza** [comment]
This is due to a known incompatibility between the conda-installed openbabel and conda/pip installed molgrid. I am working on a new conda build recipe for molgrid to try to resolve this issue, but the only current workaround is to build molgrid from source using the version of openbabel that you have installed.

Here is the repo that will contain the molgrid build recipe: https://github.com/mattragoza/conda-molgrid

The build recipe is a work in progress at this point, but you should be able to create a conda environment from the environment.yaml file in that repo, then build molgrid within that environment without too much hassle.

**Comment by hanshangjin** [comment]
I also encountered the same problem. Did you solve this problem? Thanks!

**Comment by Mingchenchen** [comment]
Hi I finally got this problem solved, largely guided by the recipe provided by the owner. https://github.com/mattragoza/conda-molgrid. But I made some modifications.
name: liGANpy38
channels:
  - anaconda
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - blosc=1.21.0=h9c3ff4c_0
  - boost=1.74.0=py38h2b96118_4
  - boost-cpp=1.74.0=hc6e9bd1_3
  - brotli=1.0.9=h7f98852_6
  - brotli-bin=1.0.9=h7f98852_6
  - brunsli=0.1=h9c3ff4c_0
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2021.10.8=ha878542_0
  - cairo=1.16.0=h6cf1ce9_1008
  - certifi=2021.10.8=py38h578d9bd_1
  - charls=2.2.0=h9c3ff4c_0
  - cloudpickle=2.0.0=pyhd8ed1ab_0
  - cmake=3.19.6=h973ab73_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - cytoolz=0.11.2=py38h497a2fe_1
  - dask-core=2021.12.0=pyhd8ed1ab_0
  - expat=2.4.2=h9c3ff4c_0
  - fontconfig=2.13.1=hba837de_1005
  - fonttools=4.28.5=py38h497a2fe_0
  - freetype=2.10.4=h0708190_1
  - fsspec=2021.11.1=pyhd8ed1ab_0
  - gettext=0.19.8.1=h73d1719_1008
  - giflib=5.2.1=h36c2ea0_2
  - greenlet=1.1.2=py38h709712a_1
  - icu=68.2=h9c3ff4c_0
  - imagecodecs=2021.3.31=py38h1455ab2_0
  - imageio=2.13.1=pyhd8ed1ab_0
  - jpeg=9d=h36c2ea0_0
  - jxrlib=1.1=h7f98852_2
  - kiwisolver=1.3.2=py38h1fd1430_1
  - krb5=1.19.2=h48eae69_3
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=2.2.1=h9c3ff4c_0
  - libaec=1.0.6=h9c3ff4c_0
  - libblas=3.9.0=12_linux64_openblas
  - libbrotlicommon=1.0.9=h7f98852_6
  - libbrotlidec=1.0.9=h7f98852_6
  - libbrotlienc=1.0.9=h7f98852_6
  - libcblas=3.9.0=12_linux64_openblas
  - libcurl=7.80.0=h494985f_1
  - libdeflate=1.7=h7f98852_5
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=11.2.0=h1d223b6_11
  - libgfortran-ng=11.2.0=h69a702a_11
  - libgfortran5=11.2.0=h5c6108e_11
  - libglib=2.70.2=h174f98d_0
  - libgomp=11.2.0=h1d223b6_11
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=12_linux64_openblas
  - libnghttp2=1.43.0=ha19adfc_1
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.18=pthreads_h8fe5266_0
  - libpng=1.6.37=h21135ba_2
  - libssh2=1.10.0=ha35d2d1_2
  - libstdcxx-ng=11.2.0=he4da1e4_11
  - libtiff=4.2.0=hbd63e13_2
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.42.0=h7f98852_0
  - libwebp-base=1.2.1=h7f98852_0
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.9.12=h72842e0_0
  - libzlib=1.2.11=h36c2ea0_1013
  - libzopfli=1.0.3=h9c3ff4c_0
  - locket=0.2.0=py_2
  - lz4-c=1.9.3=h9c3ff4c_1
  - matplotlib-base=3.5.1=py38hf4fb855_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.2=h58526e2_4
  - networkx=2.6.3=pyhd8ed1ab_1
  - numpy=1.21.5=py38h87f13fb_0
  - olefile=0.46=pyh9f0ad1d_1
  - openbabel=3.0.0=py38hdef5451_1
  - openjpeg=2.4.0=hb52868f_1
  - openssl=3.0.0=h7f98852_2
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.3.5=py38h43a58ef_0
  - partd=1.2.0=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pillow=8.2.0=py38ha0e1e83_1
  - pip=21.3.1=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pycairo=1.20.1=py38hf61ee4a_1
  - pynvml=11.4.1=pyhd8ed1ab_0
  - pyparsing=3.0.6=pyhd8ed1ab_0
  - python=3.8.12=hf930737_2_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytz=2021.3=pyhd8ed1ab_0
  - pywavelets=1.2.0=py38h6c62de6_1
  - pyyaml=6.0=py38h497a2fe_3
  - rdkit=2021.09.3=py38h8c3fb5a_0
  - readline=8.1=h46c0cb4_0
  - reportlab=3.5.68=py38hadf75a6_1
  - rhash=1.4.1=h7f98852_0
  - scikit-image=0.17.2=py38hdf5156a_0
  - scipy=1.7.3=py38h56a6a73_0
  - setuptools=60.1.0=py38h578d9bd_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.8=he1b5a44_3
  - sqlalchemy=1.4.29=py38h497a2fe_0
  - sqlite=3.37.0=h9cd32fc_0
  - tifffile=2021.4.8=pyhd8ed1ab_0
  - tk=8.6.11=h27826a3_1
  - toolz=0.11.2=pyhd8ed1ab_0
  - unicodedata2=14.0.0=py38h497a2fe_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - zfp=0.5.5=h9c3ff4c_8
  - zlib=1.2.11=h36c2ea0_1013
  - zstd=1.4.9=ha95c52a_0
  - pip:
    - attrs==21.2.0
    - iniconfig==1.1.1
    - pluggy==1.0.0
    - psutil==5.8.0
    - py==1.11.0
    - pyquaternion==0.9.9
    - pytest==6.2.5
    - toml==0.10.2
    - torch==1.9.0+cu111
    - torchaudio==0.9.0
    - torchvision==0.10.0+cu111
    - typing-extensions==4.0.1
prefix: /home2/mc70/anaconda3/envs/liGANpy38

After building this Conda environment. I follow the libmolgrid installation guide, and succeed.

**Comment by longlongman** [comment]
I also encountered the same problem. Did you solve this problem? Thanks!

**Comment by futianfan** [comment]
I also encountered the same problem. Did you solve this problem? Thanks!
