### ISSUE TITLE
colab crashed when loading data

### ISSUE THREAD

**Issue by flashasdbaksdgi** [mattragoza/liGAN#32]
![image](https://user-images.githubusercontent.com/88150931/150626040-28c0929d-bd6e-499b-ac82-12d5de825a29.png)

when I run %run generate.py config/generate.config

colab crashed,and I tried restart,but the result was still the same
could u please tell me why?

**Comment by mattragoza** [comment]
Can you provide an error message?

**Comment by flashasdbaksdgi** [comment]
> Can you provide an error message?

There seems to be no error, just a crash（ I didn't run out the RAM）：（
could you please provide an example running this project on Colab？

**Comment by flashasdbaksdgi** [comment]
problem solved ,change batch size ：5→1
