### ISSUE TITLE
"Aborted (core dumped)" error using tutorial for Generating molecules

### ISSUE THREAD

**Issue by sll513** [mattragoza/LiGAN#33]
I tried to follow the tutorial for generating molecules: python3 generate.py config/generate.config
I got the "Aborted (core dumped)" error after the output stopped at "Getting next batch of data" for a long while:
![image](https://user-images.githubusercontent.com/42878601/152558065-08f4a4ff-59b8-4aa1-9869-585c86ecf609.png)
any thought? is this due to I donot have enough memory (I have 160GB for now)

**Comment by mattragoza** [comment]
Hi there, how did you install openbabel and libmolgrid?

**Comment by sll513** [comment]
I am using this yml file
![image](https://user-images.githubusercontent.com/42878601/152560821-a43eebe7-b9b6-426e-bd77-2ea2cc233e0f.png)

**Comment by mattragoza** [comment]
This is due to an unfortunate incompatibility between the current pip/conda molgrid and conda openbabel (see #29).

For the time being, the workaround is to build libmolgrid from source. Use the environment.yaml file from [this repo](https://github.com/mattragoza/conda-molgrid) as a starting point and open an issue there if you run into issues building libmolgrid.

**Comment by sll513** [comment]
Thanks, I tried to do as you mentioned in the molgrid repo, when I am at "make -j8" step, I got the following errors:
[ 82%] Linking CXX executable ../bin/test_grid_cu
/home/sicun/miniconda3/envs/molgrid/bin/../lib/gcc/x86_64-conda-linux-gnu/9.4.0/../../../../x86_64-conda-linux-gnu/bin/ld: /usr/lib64/libz.so: undefined reference to `memcpy@GLIBC_2.14'
collect2: error: ld returned 1 exit status
make[2]: *** [test/CMakeFiles/test_grid_cu.dir/build.make:109: bin/test_grid_cu] Error 1
make[1]: *** [CMakeFiles/Makefile2:1060: test/CMakeFiles/test_grid_cu.dir/all] Error 2

**Comment by sll513** [comment]
I have ldd (GNU libc) 2.17
