### ISSUE TITLE
cuda error 

### ISSUE THREAD

**Issue by INHYEOKSONG** [mattragoza/liGAN#41]
Until last Friday, the generation using the pre-trained model was working well. From yesterday RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemv(handle, op, m, n, &alpha, a, lda, x, incx, &beta, y, incy)` I wonder if this has ever happened.

libmolgrid was also built via conda-molgrid.

**Comment by lh12565** [comment]
> Until last Friday, the generation using the pre-trained model was working well. From yesterday RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemv(handle, op, m, n, &alpha, a, lda, x, incx, &beta, y, incy)` I wonder if this has ever happened.
> 
> libmolgrid was also built via conda-molgrid.

Hi @INHYEOKSONG I met the same error as you, how did you solve it? Thanks!
