### ISSUE TITLE
How to use PDB of Alphafold2 to drug discovery?

### ISSUE THREAD

**Issue by lh12565** [mattragoza/liGAN#44]
Hi @mattragoza I want to use pdb of alphafold2 to find molecules. Do I only need to change two parameters: data_root and data_file in config/generate.config? Is the 'crossdock2020'   the default reference files? for example:

data_root: data/
data_file: data/alphafold.pdb

Thanks!

**Comment by lh12565** [comment]
> Please refer to #40. I will update the readme with better instructions for this usage, as well.

Hi @mattragoza there is no ligand in pdb of alphafold. My parameter file (data_file) is as follows:
1 0 0 data/alphafold.pdb 0 #0
As I have no ligand and RMSD, Is that right?
Thanks!

**Comment by mattragoza** [comment]
You still need to provide a ligand structure file to the model, even if you are only interested in prior sampling. You can use something like `tests/input/O_0_0_0.sdf`, which just contains a single oxygen atom.
