### ISSUE TITLE
feedback about generated molecules

### ISSUE THREAD

**Issue by annie20220104** [mattragoza/liGAN#45]
Hi,
thank you for publishing this fantastic work. 
May I give some feedback about the generated molecules?  I tested liGAN (posterior and prior model) on our protein target with reference molecule, and the test sets in the demo. When I view the SMILES of the generated molecules, it seems that a high ratio of the molecules have weird structures. Is it normal? For example, it occurs quite often that the structures have multi-fused cyclic compounds, which are not so realistic. Another example is that a super big ring (which may contain 7 or 8 atoms) shows up.

Bests
Chencheng

**Comment by mattragoza** [comment]
The approach we recommend is to generate many samples (100-1000) and then filter the molecules based on some criteria such as drug-likeness. You can also get more realistic molecules by reducing the variability factor, though they tend to be more similar to the reference molecule.

**Comment by annie20220104** [comment]
Thank you very much for your kind reply.

Bests
