### ISSUE TITLE
Aborted (core dumped) when generate molecules

### ISSUE THREAD

**Issue by Matheo-Chang** [mattragoza/LiGAN#47]
Hello, when I use generate.py config/generate.config. It appears a problem as follows, and i couldn't locate the problem. Do you have some advices?
```
Setting random seed to 0
Loading data
Initializing generative model
Loading generative model state
Initializing atom fitter
Initializing bond adder
Initializing output writer
Empty DataFrame
Columns: []
Index: []
Starting to generate grids
0 0 0 0
Calling generator forward
  prior = 0
  stage2 = False
Getting next batch of data
Aborted (core dumped)
```

**Comment by mattragoza** [comment]
How did you install the dependencies?

**Comment by Matheo-Chang** [comment]
> How did you install the dependencies?
I install all these dependencies without molgrid with conda, and molgrid with pip.
I find that the problem locate in atom_types.py: line 263
`super().__init__(
            lambda a: (self.get_type_vector(a), self.get_radius(a)),
            self.n_types
        )`
and if I do anything about class ob_atom (like ob_atom.getY()), the process will be got stuck, and i can't do anything.

**Comment by mattragoza** [comment]
You should use the `environment.yaml` file that is now provided in the repo to create a conda environment (preferably using mamba), then build molgrid from source in the conda environment. Step-by-step instructions can be found in the README.md.

**Comment by Matheo-Chang** [comment]
Excuse me, I think there is also a problem in the environment that you have updated. “Getting next batch of data==============================*** Open Babel Warning  in PerceiveBondOrders  Failed to kekulize aromatic bonds in OBMol::PerceiveBondOrders (title is data/crossdock2020/B4GT1_HUMAN_125_398_0/2ah9_B_rec.pdb)Getting real input molecule from data root[11:02:56] Molecule does not have explicit Hs. Consider calling AddHs().Minimizing real molecule with gninaTraceback (most recent call last):  File "/da1/home/changhaoyu/LiGAN/generate.py", line 47, in <module>    main(sys.argv[1:])  File "/da1/home/changhaoyu/LiGAN/generate.py", line 42, in main    generator.generate(**config['generate'])  File "/da1/home/changhaoyu/LiGAN/ligan/generating.py", line 370, in generate    input_lig_mol.gnina_minimize(rec_mol=input_rec_mol)  File "/da1/home/changhaoyu/LiGAN/ligan/molecules.py", line 184, in gnina_minimize    return gnina_minimize_rd_mol(self, *args, **kwargs)  File "/da1/home/changhaoyu/LiGAN/ligan/molecules.py", line 792, in gnina_minimize_rd_mol    proc = Popen(shlex.split(cmd), stdout=PIPE, stderr=PIPE)  File "/home/changhaoyu/anaconda3/envs/LiGAN/lib/python3.9/subprocess.py", line 951, in __init__    self._execute_child(args, executable, preexec_fn, close_fds,  File "/home/changhaoyu/anaconda3/envs/LiGAN/lib/python3.9/subprocess.py", line 1821, in _execute_child    raise child_exception_type(errno_num, err_msg, err_filename)FileNotFoundError: [Errno 2] No such file or directory: '/net/pulsar/home/koes/dkoes/local/bin/gnina'”---- Replied Message ----FromMatt ***@***.***>Date07/15/2022 03:57 ***@***.***> ***@***.******@***.***>SubjectRe: [mattragoza/liGAN] Aborted (core dumped) when generate molecules (Issue #47)
You should use the environment.yaml file that is now provided in the repo to create a conda environment (preferably using mamba), then build molgrid from source in the conda environment. Step-by-step instructions can be found in the README.md.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/mattragoza/liGAN/issues/47#issuecomment-1184842160",
"url": "https://github.com/mattragoza/liGAN/issues/47#issuecomment-1184842160",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by mattragoza** [comment]
The last dependency you need is [gnina](https://github.com/gnina/gnina), which is used for the final minimization and affinity prediction with respect to the conditional receptor.

I just updated the main branch with the option to turn off gnina minimization using the setting `generate: gnina_minimize: false` in `config/generate.config`.

Gnina is available as a standalone binary which you can download [here](https://github.com/gnina/gnina/releases/download/v1.0/gnina), as a Docker image available [here](https://hub.docker.com/u/gnina), or by building from source. I will update the README.md with this missing step.

**Comment by RMeli** [comment]
If you want to minimise with Gnina, you also need to set the `GNINA_CMD` variable to point to your Gnina executable, see PR #26

**Comment by mattragoza** [comment]
@RMeli I pushed a commit so that we used `GNINA_CMD` if it is defined in the environment, otherwise just `gnina` is run.
