### ISSUE TITLE
where is the output for generated molecules and matrix?

### ISSUE THREAD

**Issue by sll513** [mattragoza/LiGAN#49]
I just installed ligan, and ran python3 generate.py config/generate.config

everything is fine. I think I finished the run, now I am wondering where is the output files with generated molecules? do we have some post-analysis scripts available? like evaluation matrix and score for the generated molecules? Thanks,

**Comment by sll513** [comment]
Also, as you mentioned in ticket, if I want to generate large amount of molecules, which parameter shall I play around? multiple random seeds, n_examples, or n_samples? Thanks,

**Comment by mattragoza** [comment]
If you set the config option `output: output_mols: True`, then the 3D molecules will be written to sdf files in the directory `{out_dir}/molecules/`. Computed metrics for the generated molecules will be written to a file `{out_prefix}.gen_metrics`. The metrics are not currently documented well, but any column name that begins with "lig_gen_*" is a metric computed on a generated grid/structure/molecule. For instance, `lig_gen_fit_add_QED` is the drug-likeness score for the generated molecule.

The `n_examples` option specifies the number of distinct input examples (receptor-ligand pairs) from your data file you would like to generate molecules for, and the `n_samples` option specifies the number of random samples to generate for each input example. The total number of output molecules will be `n_examples * n_samples`. The `random_seed` option is for reproducibility.

**Comment by sll513** [comment]
@mattragoza  Thanks for the reply. in the {out_dir}/molecules/, which is the final optimized 3D structure in terms of to the binding pocket. Is it *lig_gen_fit_add_gna.sdf? I have other sdf files in the same folder: *add_uff.sdf, *add_pkt.sdf, and *add.sdf

Thanks

**Comment by mattragoza** [comment]
Yes, the files ending in `lig_gen_fit_add_gna.sdf` are the generated molecules after minimization in the binding pocket with gnina.

Here are all the output identifier types and what they mean:
```
lig_gen = generated density grid (from generative model)
lig_gen_fit = generated atoms (from atom fitting)
lig_gen_fit_add = generated molecule (from bond adding)
lig_gen_fit_add_uff = generated molecule after UFF minimization (internal energy)
lig_gen_fit_add_gna = generated molecule after gnina minimization (wrt binding pocket)
lig_gen_fit_add_pkt = receptor pocket used for gnina minimization
```
