### ISSUE TITLE
gnina minmize problem

### ISSUE THREAD

**Issue by INHYEOKSONG** [mattragoza/LiGAN#50]
hello. Thank you for sharing liGAN. I applied gnina mimize to liGAN a few months ago and used it well, but like the method you shared while setting up the new one, I cloned the most recent LiGAN git and build molgrid and liGAN normally. 1) sh download_weights.sh
2) python3 generate.py config/generate.config

Installed gnina confirmed working 2nd photo.

I ran it as before through the command. However, the generation process did not proceed because of gnina, which was used a few months ago. Please check once
![스크린샷 2022-08-01 오후 2 59 49](https://user-images.githubusercontent.com/98927406/182085750-0efa14b7-9847-4437-b9be-e0b2cc17b522.png)
![스크린샷 2022-08-02 오후 4 03 19](https://user-images.githubusercontent.com/98927406/182312760-285d5691-f3f8-45c4-94e5-dac75d742069.png)

**Comment by INHYEOKSONG** [comment]
sorry. This issue has been resolved.

**Comment by mattragoza** [comment]
Notice the message in the GNINA STDERR section: "Runtime Error: all CUDA-capable devices are busy or unavailable"

For anyone else who runs into this issue, was that indeed the problem?
