### ISSUE TITLE
Can not access to https://bits.csb.pitt.edu/files/ to download those files

### ISSUE THREAD

**Issue by Hovi123123** [mattragoza/LiGAN#51]
Excuse me, there are some problems happend when I was attempt to use `sh download_weights.sh` to download the model`s weights. The web(https://bits.csb.pitt.edu) appears to be out of service resulting in the inability to download the required files. Would you please check it out ? Thanks !

**Comment by mattragoza** [comment]
Apparently there was an outage at 10pm last night and they are working on restoring connectivity. See https://github.com/gnina/models/issues/22.

**Comment by Hovi123123** [comment]
> Apparently there was an outage at 10pm last night and they are working on restoring connectivity. See [gnina/models#22](https://github.com/gnina/models/issues/22).

OK，thanks for your help :-)
