### ISSUE TITLE
tests ValueError: File does not exist: data/test_pockets/xxx

### ISSUE THREAD

**Issue by zyx5256** [mattragoza/LiGAN#53]
ERROR tests/test_generating.py::TestGenerator::test_generator_init[data/test_pockets/AROK_MYCTU_1_176_0/fixed_input_1zyu_A_rec_mutants.types] - ValueError: Could not open ...
ERROR tests/test_generating.py::TestGenerator::test_generator_init[data/test_pockets/AROK_MYCTU_1_176_0/fixed_cond_1zyu_A_rec_mutants.types] - ValueError: Could not open f...
ERROR tests/test_generating.py::TestGenerator::test_gen_forward[data/test_pockets/AROK_MYCTU_1_176_0/fixed_input_1zyu_A_rec_mutants.types] - ValueError: Could not open fil...
ERROR tests/test_generating.py::TestGenerator::test_gen_forward[data/test_pockets/AROK_MYCTU_1_176_0/fixed_cond_1zyu_A_rec_mutants.types] - ValueError: Could not open file...
ERROR tests/test_generating.py::TestGenerator::test_gen_forward2[data/test_pockets/AROK_MYCTU_1_176_0/fixed_input_1zyu_A_rec_mutants.types] - ValueError: Could not open fi...
ERROR tests/test_generating.py::TestGenerator::test_gen_forward2[data/test_pockets/AROK_MYCTU_1_176_0/fixed_cond_1zyu_A_rec_mutants.types] - ValueError: Could not open fil...
ERROR tests/test_generating.py::TestGenerator::test_generate[data/test_pockets/AROK_MYCTU_1_176_0/fixed_input_1zyu_A_rec_mutants.types] - ValueError: Could not open file d...
ERROR tests/test_generating.py::TestGenerator::test_generate[data/test_pockets/AROK_MYCTU_1_176_0/fixed_cond_1zyu_A_rec_mutants.types] - ValueError: Could not open file da...

**Comment by zyx5256** [comment]
the log is shown above. I notice that there's no "test_pockets" directory under tests/, neither does those files. How can I get them? Or maybe I should just skip those ut tests...

**Comment by mattragoza** [comment]
You can ignore this, but thanks for bringing it to my attention. I'll add those test input files to the repo.

**Comment by mattragoza** [comment]
I have added the missing data files to the repo, so all the tests should pass now.
